export const indianCities = [
	'Mumbai',
	'Delhi',
	'Bengaluru',
	'Hyderabad',
	'Ahmedabad',
	'Chennai',
	'Kolkata',
	'Surat',
	'Pune',
	'Jaipur',
	'Lucknow',
	'Kanpur',
	'Nagpur',
	'Indore',
	'Thane',
	'Bhopal',
	'Visakhapatnam',
	'Patna',
	'Vadodara',
	'Ghaziabad',
	'Ludhiana',
	'Agra',
	'Nashik',
	'Faridabad',
	'Meerut',
	'Rajkot',
	'Varanasi',
	'Srinagar',
	'Prayagraj',
	'Ranchi',
	'Coimbatore',
	'Jabalpur',
	'Gwalior',
	'Vijayawada',
	'Jodhpur',
	'Madurai',
	'Raipur',
	'Kota',
	'Chandigarh',
	'Guwahati',
	'Solapur',
	'Hubballi',
	'Mysuru',
	'Tiruchirappalli',
	'Gurugram',
	'Noida',
	'Amritsar',
	'Navi Mumbai',
	'Bhubaneswar',
	'Kochi'
] as const;

export type IndianCity = (typeof indianCities)[number];

export function isIndianCity(value: string): value is IndianCity {
	return (indianCities as readonly string[]).includes(value);
}
